products = [
    {
        '_id': '1',
        'name': 'Neon 1',
        'image': '/images/neon1.jpg',
        'description': 'Neon Sign 1',
        'brand': 'Neo',
        'category': 'Category x',
        'price': '11.11',
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Neon 2',
        'image': '/images/neon2.jpg',
        'description': 'Neon Sign 2',
        'brand': 'Neo',
        'category': 'Category z',
        'price': '11.11',
        'countInStock': 8,
        'rating': 4.0,
        'numReviews': 33,
    },
    {
        '_id': '3',
        'name': 'Neon 3',
        'image': '/images/neon3.jpg',
        'description': 'Neon Sign 3',
        'brand': 'Neo',
        'category': 'Category x',
        'price': '36.99',
        'countInStock': 7,
        'rating': 5.0,
        'numReviews': 22,
    },
    {
        '_id': '4',
        'name': 'Neon 4',
        'image': '/images/neon4.jpg',
        'description': 'Neon Sign 4',
        'brand': 'Neo',
        'category': 'Category z',
        'price': '99.99',
        'countInStock': 6,
        'rating': 3.9,
        'numReviews': 11,
    },
    {
        '_id': '5',
        'name': 'Neon 5',
        'image': '/images/neon5.jpg',
        'description': 'Neon Sign 5',
        'brand': 'Neo',
        'category': 'Category x',
        'price': '22.99',
        'countInStock': 11,
        'rating': 4.6,
        'numReviews': 11,
    },
    {
        '_id': '6',
        'name': 'Neon 6',
        'image': '/images/neon6.jpg',
        'description': 'Neon Sign 6',
        'brand': 'Neo',
        'category': 'Category z',
        'price': '19.99',
        'countInStock': 10,
        'rating': 4.8,
        'numReviews': 9,
    },
]
